# utils/export/export_client_docx_fancy.py

from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from datetime import datetime
from bs4 import BeautifulSoup

def add_clean_html_paragraphs(doc, html_text):
    soup = BeautifulSoup(html_text, "html.parser")
    for elem in soup.contents:
        if elem.name == "h3":
            para = doc.add_paragraph()
            run = para.add_run(elem.get_text())
            run.bold = True
            run.font.size = Pt(14)
        elif elem.name == "b":
            para = doc.add_paragraph()
            run = para.add_run(elem.get_text())
            run.bold = True
        elif elem.name == "em":
            para = doc.add_paragraph()
            run = para.add_run(elem.get_text())
            run.italic = True
        elif elem.name == "ul":
            for li in elem.find_all("li"):
                doc.add_paragraph(li.get_text(), style='List Bullet')
        elif elem.name == "br":
            doc.add_paragraph("")
        elif elem.string and elem.string.strip():
            doc.add_paragraph(elem.string.strip())

def export_client_docx_fancy(df, proposal_text, buffer, client_name="Client Name", user="Cameron Rodrigues", firm="Procyon Partners", logo_path=None):
    doc = Document()
    style = doc.styles['Normal']
    style.font.name = 'Times New Roman'
    style.font.size = Pt(12)

    # Header
    section = doc.sections[0]
    header = section.header
    header_paragraph = header.paragraphs[0]
    header_paragraph.text = f"Generated by FidSync – {datetime.now().strftime('%B %d, %Y')}"
    header_paragraph.alignment = WD_PARAGRAPH_ALIGNMENT.RIGHT

    if logo_path:
        doc.add_picture(logo_path, width=Inches(2.5))

    # Title
    title = doc.add_paragraph("Client Proposal")
    title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    title.runs[0].font.size = Pt(18)
    title.runs[0].bold = True

    doc.add_paragraph(f"Prepared for: {client_name}")
    doc.add_paragraph(f"Prepared by: {user} | {firm}")
    doc.add_paragraph("")

    doc.add_paragraph("Proposal Summary", style="Heading 1")
    add_clean_html_paragraphs(doc, proposal_text)

    # Fund Table
    doc.add_paragraph("\nFund Performance Overview", style="Heading 1")
    table = doc.add_table(rows=1, cols=len(df.columns))
    table.style = 'Table Grid'
    hdr_cells = table.rows[0].cells
    for i, col in enumerate(df.columns):
        hdr_cells[i].text = col

    for _, row in df.iterrows():
        row_cells = table.add_row().cells
        for i, val in enumerate(row):
            row_cells[i].text = str(round(val, 2)) if isinstance(val, float) else str(val)

    # Disclaimer
    doc.add_paragraph("")
    disclaimer = doc.add_paragraph(
        "This proposal was generated automatically by FidSync and should be reviewed manually for accuracy before distribution."
    )
    disclaimer.runs[0].italic = True

    # Footer with page number
    footer = section.footer.paragraphs[0]
    footer.text = "Page "
    footer.add_run().add_field('PAGE')
    footer.add_run(" of ")
    footer.add_run().add_field('NUMPAGES')
    footer.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    doc.save(buffer)
