[theme]
base = "light"
primaryColor = "#1F4E79"
backgroundColor = "#F9FBFC"
secondaryBackgroundColor = "#E8F0F9"
textColor = "#1A1A1A"
font = "sans serif"

[server]
headless = true
runOnSave = true
enableCORS = false
enableXsrfProtection = false
