[theme]
base = "dark"
primaryColor = "#4c9cff"
backgroundColor = "#0e0e0e"  # main area background
secondaryBackgroundColor = "#f0f2f6"  # force sidebar to stay light
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
runOnSave = true
maxUploadSize = 500

[client]
toolbarMode = "minimal"
showSidebarNavigation = true

[browser]
gatherUsageStats = false
