[theme]
primaryColor = "#1E3A8A"         # Deep blue
backgroundColor = "#F9FAFB"      # Soft gray
secondaryBackgroundColor = "#E5E7EB"  # Slight contrast
textColor = "#111827"            # Very dark gray (not pure black)
font = "sans serif"

[server]
runOnSave = true

[client]
showSidebarNavigation = true
toolbarMode = "minimal"
showErrorDetails = true
