[theme]
base = "dark"
primaryColor = "#4c9cff"
backgroundColor = "#0e0e0e"              # Dark main area
secondaryBackgroundColor = "#f0f2f6"     # Force sidebar light
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
runOnSave = true
maxUploadSize = 100

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
