[theme]
base = "light"
primaryColor = "#1c2e4a"               # FidSync navy
backgroundColor = "#ffffff"            # Clean white
secondaryBackgroundColor = "#eef2f7"   # Soft cool-gray background for layout cards/containers
textColor = "#1c2e4a"                  # Consistent deep blue text
font = "sans serif"

# Note: [theme.accent] and [theme.chart] are not valid and have been removed.

[server]
headless = true
runOnSave = true
maxUploadSize = 100

[client]
toolbarMode = "minimal"
showErrorDetails = false

[browser]
gatherUsageStats = false
