[theme]
base = "light"
primaryColor = "#1c2e4a"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#1c2e4a"
font = "sans serif"

[server]
headless = true
runOnSave = true
maxUploadSize = 100

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
