[gspread]
type = "service_account"
project_id = "fidsync-integration"
private_key_id = "c7b8c13b084c956e1f9f26de9f0b80b10facb04b"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDHQAkjWUNuxtiZ
yNcsvKHGdo+FQ9fCEFi+gzgZPFKqjziVsin05UHOuRoubSpaukjiJSx9Wh8002Ob
sTbXLCZrHPCjN8MkDgyx1AtX8vuGN3dLXh3kdN7TQUmiVjOf+af9JLk2bDiwKBg8
IYVs6jbZb+tuUhVMg5k2ZJO6H3coq14bQhuu15t+kWinWSUVer3+er7/KVPKNFJA
vmsh16G/W0soBZAGUoVpk9fgaJQY/B4KAHOvbF9QurdrrnE6xZrh2OyHlHfQXPGm
TuoZRGIlY6Ulzs8Nl/u0gWUWq5LyuMhJsNJyUdbAoa2vW8vb64ou3m5nno0W3CPc
LWtq9bnvAgMBAAECggEADWG6G2Mn2b1GF9H6zZjfnpYg3njneTOi2iyy7FL2VFkp
Gjisg7OP/2PEI+EWCqDfOzz253ZRiTk3Q+IbhkkDTYdUjAm3M+kzpg/RMTdy+Bkq
jGfGRy0oN/T3Do2Oiwx34VMBk2uiRQZ0VjmEHgP+6gyPucmOf6SI+jO4DjSFyrfV
LyB3nQXAGILd59h9rgckrrPPfZBC+O3GzkfA2Ue+ySYRSAF0V14gKbRM9K5FRNwr
6E73DFTINR+gDmB3swdfMBMeQ5kbCcaicm8Mzp/wQSmyjISEdMO0xZGNA1rrFHo5
5No4JxMMJN2ps+LCf2hMYmr4+UsgKF0yj9PvQs1d4QKBgQD5GlRDkWfBov/ZdpS4
Gv3bkiO50bsjLUNCqYVV6p1nF/m97/tJKjq1gMxTQZym4czmU8hQkkMQtGzy2CXM
D4JAX40WJiPFlet/APRbz2GHzjFj4HsVAoaiMMidopnGg7K1pemXKnQ4eVV8/Q9s
ginnqe/za2oqBU3Tikg0Vjr+YQKBgQDMxFg1YNrGYyV4WXyYGr+6vJMmBGlcQKc1
6oleNQMHkI+euK5F/2Y2dXI+RkLImFGEhA/eSoItJNHX4s6jgvedMd6W6c7/eWwr
1GguSDbYiB0DdhAdbPlbEaW576rxX2OxJ9uHoV2IaiXbg/IGS31Ofd+KASv00rhl
9GZyKOd6TwKBgQDhHm1GfvLQqRklEyhF1YbT1xdYR/UiTjZ52S+5vISxdZZqk6V5
sqNKAnMlTqdenbOJ9++Q+Q2I3DWVpcdKyj1BJdkgSimL1/fyWA99pUYT8EDsbSNu
klDP5Nx4sUjdgYmQ5bbbuS89FlIu2ZgFzQBH72j9iHZyMUbrRQ4J1mAMIQKBgCMQ
0KY7ctucaPNGJ88IbaL13iEZik1xCPFzu5h1bZJjECU3LSjxhrh2vlypvZAKfZM6
5ljD260NbB4TSh24NN0niB3B5l/blEmhM0IRvcqw7H8GPdY8LiuJRx8jStvQ4Qqa
b763RIQy4U7JNq4bSVciuSAx+SwQ1eEnzE9qb9GDAoGBALOcUw4rU+PgKmPH342S
PDzO+CcN0PEGDmbQfeVqvKpFr42vD7uQk4HLPQgvX3f5mUPOi72B1v9iJnbaGJ1e
CJEd1T+Xtw9Bba5OMwt0TVjDIr4K9+hO2fs/V4ykv6Mk4d2AXj4b3rSyJJLrdAgN
6cdExOjcGmunoArazqle+l23
-----END PRIVATE KEY-----"""
client_email = "fidsync-app@fidsync-integration.iam.gserviceaccount.com"
client_id = "109646688474393509122"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/fidsync-app%40fidsync-integration.iam.gserviceaccount.com"
universe_domain = "googleapis.com"


[together]
api_key = "d481caa423d713c53524e72f2ef6b6ff52a25a35ee393a38c8f2de29c3f9b238"

